'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {usePathname} from 'next/navigation'

const en=[['Haircuts & Styling','haircuts-styling'],['Hair Color','hair-color'],['Highlights & Balayage','highlights-balayage'],['Blowouts','blowouts'],['Hair Treatments','hair-treatments'],['Bridal & Special Events','bridal-special-events'],['Makeup Services','makeup-services']]
const es=[['Cortes y peinados','cortes-y-peinados'],['Coloración del cabello','color-de-cabello'],['Luces y balayage','luces-y-balayage'],['Secado y peinado','brushing'],['Tratamientos capilares','tratamientos-para-el-cabello'],['Novias y eventos especiales','novias-y-eventos-especiales'],['Maquillaje','servicios-de-maquillaje']]
function languageHref(path:string, spanish:boolean){
  if(spanish){
    if(path==='/es') return '/'
    const rest=path.replace(/^\/es\/?/,'')
    if(rest.startsWith('servicios/')){const slug=rest.split('/')[1];const i=es.findIndex(x=>x[1]===slug);return i>=0?`/services/${en[i][1]}`:'/services'}
    const map:Record<string,string>={servicios:'services',gallery:'gallery',about:'about',reviews:'reviews',faq:'faq',contacto:'contact',agendar:'book','politica-de-privacidad':'privacy-policy','terminos-de-servicio':'terms-of-service'}
    return `/${map[rest]||''}`.replace(/\/$/,'')||'/'
  }
  if(path==='/') return '/es'
  const rest=path.replace(/^\//,'')
  if(rest.startsWith('services/')){const slug=rest.split('/')[1];const i=en.findIndex(x=>x[1]===slug);return i>=0?`/es/servicios/${es[i][1]}`:'/es/servicios'}
  const map:Record<string,string>={services:'servicios',gallery:'gallery',about:'about',reviews:'reviews',faq:'faq',contact:'contacto',book:'agendar','privacy-policy':'politica-de-privacidad','terms-of-service':'terminos-de-servicio'}
  return `/es/${map[rest]||''}`.replace(/\/$/,'')||'/es'
}
export default function SiteChrome({children}:{children:React.ReactNode}){const path=usePathname()||'/';const spanish=path.startsWith('/es');const base=spanish?'/es':'';const serviceBase=spanish?'/es/servicios':'/services';useEffect(()=>{document.documentElement.lang=spanish?'es':'en'},[spanish]);const items=spanish?es:en;const[open,setOpen]=useState(false);const[drop,setDrop]=useState(false);const close=()=>{setOpen(false);setDrop(false)};return <><header className="site-header"><Link className="logo" href={base||'/'} onClick={close}>SOL & SAGE<span>BEAUTY STUDIO</span></Link><nav id="site-nav" className={open?'mobile-open':''}><Link href={base||'/'} onClick={close}>{spanish?'Inicio':'Home'}</Link><div className="nav-services"><button id="services-toggle" type="button" aria-haspopup="true" aria-controls="services-menu" aria-expanded={drop} onClick={()=>setDrop(!drop)}>{spanish?'Servicios':'Services'} ⌄</button><div id="services-menu" className={'services-dropdown '+(drop?'show':'')}><Link href={serviceBase} onClick={close}>{spanish?'Todos los servicios':'All Services'}</Link>{items.map(([label,slug],i)=><Link key={slug} href={`${serviceBase}/${slug}`} onClick={close}>{String(i+1).padStart(2,'0')} {label}</Link>)}</div></div><Link href={`${base}/gallery`} onClick={close}>{spanish?'Galería':'Gallery'}</Link><Link href={`${base}/about`} onClick={close}>{spanish?'El estudio':'About'}</Link><Link href={`${base}/reviews`} onClick={close}>{spanish?'Opiniones':'Reviews'}</Link><Link href={`${base}/faq`} onClick={close}>{spanish?'Preguntas':'FAQ'}</Link><Link href={`${base}/${spanish?'contacto':'contact'}`} onClick={close}>{spanish?'Contacto':'Contact'}</Link></nav><div className="header-actions"><Link href={languageHref(path,spanish)} onClick={close} aria-label={spanish?'Ver esta página en inglés':'Ver esta página en español'}>EN | ES</Link><Link className="button small" href={spanish?'/es/agendar':'/book'} onClick={close}>{spanish?'Agenda una cita':'Book an Appointment'}</Link><button className="menu-toggle" aria-controls="site-nav" aria-label={spanish?(open?'Cerrar menú':'Abrir menú'):(open?'Close menu':'Open menu')} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'×':(spanish?'Menú':'Menu')}</button></div></header>{children}<footer><div><Link className="logo" href={base||'/'} onClick={close}>SOL & SAGE<span>BEAUTY STUDIO</span></Link><p>{spanish?'Belleza moderna en Santa Barbara, California.':'Modern beauty in Santa Barbara, California.'}</p></div><div className="footer-links"><Link href={`${base}/${spanish?'politica-de-privacidad':'privacy-policy'}`}>{spanish?'Privacidad':'Privacy'}</Link><Link href={`${base}/${spanish?'terminos-de-servicio':'terms-of-service'}`}>{spanish?'Términos':'Terms'}</Link><a href="tel:+18055550174">(805) 555-0174</a><a href="mailto:hello@solandsagebeauty.com">hello@solandsagebeauty.com</a></div></footer></>}
