import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'
export const metadata: Metadata={title:'Sol & Sage Beauty Studio | Santa Barbara',description:'Belleza moderna y servicios de cabello diseñados alrededor del estilo personal en el concepto ficticio Sol & Sage.',alternates:{canonical:'/es',languages:{'en-US':'/','es-US':'/es'}},openGraph: {url:'/es',images:[{url:'/images/hero.webp',width:1536,height:1024,alt:'Sol & Sage Beauty Studio in Santa Barbara'}],title:'Sol & Sage Beauty Studio | Santa Barbara',description:'Belleza moderna en Santa Barbara, California.'}}
const services=['Cortes y peinados','Coloración del cabello','Luces y balayage','Secado y peinado','Tratamientos capilares','Novias y eventos especiales','Maquillaje']
const serviceSlugs=['cortes-y-peinados','color-de-cabello','luces-y-balayage','brushing','tratamientos-para-el-cabello','novias-y-eventos-especiales','servicios-de-maquillaje']
const looks=[['/images/gallery-01.webp','Corte corto moderno'],['/images/gallery-04.webp','Luces que enmarcan el rostro'],['/images/gallery-05.webp','Recogido romántico para evento'],['/images/gallery-06.webp','Maquillaje natural y luminoso']]
export default function SpanishHome(){return <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">SANTA BARBARA · CABELLO Y BELLEZA</p><h1>Belleza moderna.<br/><em>A tu manera.</em></h1><p className="lead">Servicios personalizados de cabello y belleza pensados para tu estilo, tus momentos importantes y la confianza de sentirte tú.</p><div className="actions"><Link className="button" href="/es/agendar">Agenda una cita</Link><Link className="text-link" href="/es/servicios">Explora los servicios →</Link><Link className="text-link" href="/es/gallery">Mira nuestro trabajo →</Link></div></div><div className="hero-image"><div className="image-label">Sol & Sage / 01</div></div></section>
  <section className="intro"><p className="eyebrow">UN RITUAL MODERNO DE BELLEZA</p><h2>Detalles pensados para hacerte sentir bien.</h2><p className="lead center-copy">Un concepto de estudio ficticio creado alrededor de conversaciones tranquilas, atención a cada detalle y una belleza que se sigue sintiendo tuya.</p><Link className="text-link" href="/es/about">Conoce Sol & Sage →</Link></section>
  <section className="services"><div className="section-head"><div><p className="eyebrow">EL MENÚ</p><h2>Servicios con intención.</h2></div><Link className="text-link" href="/es/servicios">Ver todos los servicios →</Link></div><div className="service-grid">{services.map((s,i)=><Link className="service-card" href={'/es/servicios/'+serviceSlugs[i]} key={s}><span>0{i+1}</span><h3>{s}</h3><b>↗</b></Link>)}</div></section>
  <section className="home-gallery"><div className="section-head"><div><p className="eyebrow">LA GALERÍA</p><h2>Estilos recientes.</h2></div><Link className="text-link" href="/es/gallery">Ver la galería →</Link></div><div className="mini-gallery">{looks.map(([src,alt],i)=><Link href="/es/gallery" key={src}><Image src={src} alt={alt+' en un estudio de belleza de Santa Barbara'} fill sizes="(max-width:700px) 50vw, 25vw"/><span>ESTILO {String(i+1).padStart(2,'0')}</span></Link>)}</div></section>
  <section className="feature"><div className="feature-image"><span>COLORACIÓN / BALAYAGE</span></div><div className="feature-copy"><p className="eyebrow">TU ESTILO DISTINTIVO</p><h2>Color que se siente como tú.</h2><p>Desde una dimensión sutil hasta una renovación completa, cada cita de color comienza con una conversación y termina con un resultado pensado para tu vida.</p><Link className="button dark" href="/es/servicios/luces-y-balayage">Explora el color</Link></div></section>
  <section className="home-panels"><article><p className="eyebrow">POR QUÉ SOL & SAGE</p><h2>Personal, tranquilo y bien pensado.</h2><p>El concepto del estudio está diseñado para conversar con claridad, crear un plan cuidadoso y lograr un resultado que refleje tu estilo.</p><Link className="text-link" href="/es/about">Conoce el estudio →</Link></article><article><p className="eyebrow">NOVIAS Y EVENTOS ESPECIALES</p><h2>Belleza para momentos importantes.</h2><p>Explora una propuesta de demostración para peinados de evento, maquillaje y detalles que hacen que un estilo especial se sienta verdaderamente tuyo.</p><Link className="text-link" href="/es/servicios/novias-y-eventos-especiales">Explora los servicios para eventos →</Link></article></section>
  <section className="process"><p className="eyebrow">NUESTRO PROCESO</p><h2>Qué puedes esperar.</h2><div className="process-grid"><div><span>01</span><h3>Conversemos</h3><p>Cuéntanos tus objetivos, referencias, rutina y cómo quieres sentirte con el resultado.</p></div><div><span>02</span><h3>Creemos un plan</h3><p>Juntos definimos la dirección del servicio y los detalles importantes de tu visita.</p></div><div><span>03</span><h3>Hazlo tuyo</h3><p>Termina con un estilo pensado para sentirse natural en tu vida diaria.</p></div></div></section>
  <section className="home-reviews"><p className="eyebrow">LO QUE DICEN NUESTRAS CLIENTAS</p><h2>Notas desde la silla.</h2><p className="demo-note">Testimonios de muestra creados únicamente para demostración.</p><div className="quotes"><blockquote>“Una experiencia tranquila y cuidada de principio a fin.”<small>— Testimonio de muestra</small></blockquote><blockquote>“Una cita de belleza que se siente completamente personal.”<small>— Testimonio de muestra</small></blockquote></div><Link className="text-link" href="/es/reviews">Leer opiniones de muestra →</Link></section>
  <section className="home-faq"><p className="eyebrow">INFORMACIÓN ÚTIL</p><h2>Preguntas y respuestas.</h2><details><summary>¿Puedo reservar en línea desde este sitio web?<span>+</span></summary><p>Todavía no. La sección de citas es una demostración visual y no crea una reservación real ni muestra disponibilidad.</p></details><details><summary>¿Qué hago si no sé qué servicio elegir?<span>+</span></summary><p>Comienza por contarnos el resultado que buscas. Las páginas de servicios pueden ayudarte a preparar tus preguntas.</p></details><Link className="text-link" href="/es/faq">Ver todas las preguntas →</Link></section>
  <section className="cta"><p className="eyebrow">CUANDO QUIERAS</p><h2>Haz espacio para<br/><em>tu próximo estilo.</em></h2><Link className="button dark" href="/es/agendar">Agenda una cita</Link></section>
 </main>}
