import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'
export const metadata: Metadata={title:'Sol & Sage Beauty Studio | Santa Barbara',description:'Belleza moderna y servicios de cabello diseñados alrededor del estilo personal en el concepto ficticio Sol & Sage.',alternates:{canonical:'/es',languages:{'en-US':'/','es-US':'/es'}},openGraph: {url:'/es',images:[{url:'/images/hero.webp',width:1536,height:1024,alt:'Sol & Sage Beauty Studio in Santa Barbara'}],title:'Sol & Sage Beauty Studio | Santa Barbara',description:'Belleza moderna en Santa Barbara, California.'}}
const services=['Cortes y Peinados','Color de Cabello','Luces y Balayage','Brushing','Tratamientos para el Cabello','Novias y Eventos Especiales','Servicios de Maquillaje']
const serviceSlugs=['cortes-y-peinados','color-de-cabello','luces-y-balayage','brushing','tratamientos-para-el-cabello','novias-y-eventos-especiales','servicios-de-maquillaje']
const looks=[['/images/gallery-01.webp','Corte corto moderno'],['/images/gallery-04.webp','Luces que enmarcan el rostro'],['/images/gallery-05.webp','Recogido romántico para evento'],['/images/gallery-06.webp','Maquillaje natural y luminoso']]
export default function SpanishHome(){return <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">SANTA BARBARA · CABELLO Y BELLEZA</p><h1>Belleza moderna.<br/><em>A tu manera.</em></h1><p className="lead">Servicios personalizados de cabello y belleza pensados para tu estilo, tus momentos y tu confianza diaria.</p><div className="actions"><Link className="button" href="/es/agendar">Agenda una Cita</Link><Link className="text-link" href="/es/servicios">Explora los Servicios →</Link><Link className="text-link" href="/es/gallery">Ver nuestro trabajo →</Link></div></div><div className="hero-image"><div className="image-label">Sol & Sage / 01</div></div></section>
  <section className="intro"><p className="eyebrow">UN RITUAL MODERNO DE BELLEZA</p><h2>Detalles pensados para cómo quieres sentirte.</h2><p className="lead center-copy">Un concepto de estudio ficticio creado alrededor de una conversación tranquila, detalles considerados y belleza que sigue sintiéndose tuya.</p><Link className="text-link" href="/es/about">Conoce Sol & Sage →</Link></section>
  <section className="services"><div className="section-head"><div><p className="eyebrow">EL MENÚ</p><h2>Servicios con intención.</h2></div><Link className="text-link" href="/es/servicios">Ver todos los servicios →</Link></div><div className="service-grid">{services.map((s,i)=><Link className="service-card" href={'/es/servicios/'+serviceSlugs[i]} key={s}><span>0{i+1}</span><h3>{s}</h3><b>↗</b></Link>)}</div></section>
  <section className="home-gallery"><div className="section-head"><div><p className="eyebrow">EL LOOKBOOK</p><h2>Looks recientes.</h2></div><Link className="text-link" href="/es/gallery">Ver la galería →</Link></div><div className="mini-gallery">{looks.map(([src,alt],i)=><Link href="/es/gallery" key={src}><Image src={src} alt={alt+' en un estudio de belleza de Santa Barbara'} fill sizes="(max-width:700px) 50vw, 25vw"/><span>LOOK {String(i+1).padStart(2,'0')}</span></Link>)}</div></section>
  <section className="feature"><div className="feature-image"><span>COLOR / BALAYAGE</span></div><div className="feature-copy"><p className="eyebrow">TU LOOK DISTINTIVO</p><h2>Color que se siente como tú.</h2><p>Desde una dimensión sutil hasta un refresh completo, cada cita de color comienza con una conversación y termina con un look pensado para tu vida.</p><Link className="button dark" href="/es/servicios/luces-y-balayage">Explora el color</Link></div></section>
  <section className="home-panels"><article><p className="eyebrow">POR QUÉ SOL & SAGE</p><h2>Personal, tranquilo y pensado.</h2><p>El concepto del estudio está diseñado para conversar con claridad, crear un plan considerado y encontrar un resultado conectado con tu estilo.</p><Link className="text-link" href="/es/about">Sobre el estudio →</Link></article><article><p className="eyebrow">NOVIAS Y EVENTOS ESPECIALES</p><h2>Belleza para momentos importantes.</h2><p>Explora un concepto demo para styling de eventos, maquillaje y detalles que ayudan a que un look especial se sienta intencional.</p><Link className="text-link" href="/es/servicios/novias-y-eventos-especiales">Explora belleza para eventos →</Link></article></section>
  <section className="process"><p className="eyebrow">NUESTRO PROCESO</p><h2>Qué puedes esperar.</h2><div className="process-grid"><div><span>01</span><h3>Conversemos</h3><p>Comienza con tus objetivos, referencias, rutina y la sensación que quieres lograr.</p></div><div><span>02</span><h3>Armemos el plan</h3><p>Usa la conversación del servicio para organizar la dirección de tu visita.</p></div><div><span>03</span><h3>Hazlo tuyo</h3><p>Termina con un look pensado para sentirse natural en tu vida diaria.</p></div></div></section>
  <section className="home-reviews"><p className="eyebrow">PALABRAS AMABLES</p><h2>Notas desde la silla.</h2><p className="demo-note">Testimonios de ejemplo utilizados únicamente para demostración.</p><div className="quotes"><blockquote>“Una experiencia tranquila y pensada de principio a fin.”<small>— Testimonio de muestra</small></blockquote><blockquote>“Una cita de belleza que se siente completamente personal.”<small>— Testimonio de muestra</small></blockquote></div><Link className="text-link" href="/es/reviews">Leer opiniones de muestra →</Link></section>
  <section className="home-faq"><p className="eyebrow">BUENO SABER</p><h2>Preguntas y respuestas.</h2><details><summary>¿Puedo reservar en línea desde este website?<span>+</span></summary><p>Todavía no. La reservación es una demostración visual y no crea una cita real ni muestra disponibilidad.</p></details><details><summary>¿Y si no sé qué servicio elegir?<span>+</span></summary><p>Comienza con una conversación sobre tu objetivo. Las páginas de servicios ayudan a organizar tus preguntas.</p></details><Link className="text-link" href="/es/faq">Ver todas las preguntas →</Link></section>
  <section className="cta"><p className="eyebrow">CUANDO ESTÉS LISTA</p><h2>Haz espacio para<br/><em>tu próximo look.</em></h2><Link className="button dark" href="/es/agendar">Agenda una Cita</Link></section>
 </main>}
