import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'

export const metadata: Metadata={title:'Sol & Sage Beauty Studio | Santa Barbara',description:'Modern hair and beauty services designed around personal style in the Sol & Sage Beauty Studio concept for Santa Barbara.',alternates:{canonical:'/',languages:{'en-US':'/','es-US':'/es'}},openGraph: {url:'/',images:[{url:'/images/hero.webp',width:1536,height:1024,alt:'Sol & Sage Beauty Studio in Santa Barbara'}],title:'Sol & Sage Beauty Studio | Santa Barbara',description:'Modern hair and beauty in Santa Barbara, California.'}}
const services=['Haircuts & Styling','Hair Color','Highlights & Balayage','Blowouts','Hair Treatments','Bridal & Special Events','Makeup Services']
const serviceSlugs=['haircuts-styling','hair-color','highlights-balayage','blowouts','hair-treatments','bridal-special-events','makeup-services']
const looks=[['/images/gallery-01.webp','Modern short haircut'],['/images/gallery-04.webp','Face-framing highlights'],['/images/gallery-05.webp','Romantic event updo'],['/images/gallery-06.webp','Natural luminous makeup']]
export default function Home(){return <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">SANTA BARBARA · HAIR & BEAUTY</p><h1>Modern beauty.<br/><em>Effortlessly you.</em></h1><p className="lead">Personalized hair and beauty services designed around your natural style, your moments, and your everyday confidence.</p><div className="actions"><Link className="button" href="/book">Book an Appointment</Link><Link className="text-link" href="/services">Explore Services →</Link><Link className="text-link" href="/gallery">View Our Work →</Link></div></div><div className="hero-image"><div className="image-label">Sol & Sage / 01</div></div></section>
  <section className="intro"><p className="eyebrow">A MODERN BEAUTY RITUAL</p><h2>Thoughtful artistry for the way you want to feel.</h2><p className="lead center-copy">A fictional studio concept built around a calm conversation, considered details, and beauty that still feels like your own.</p><Link className="text-link" href="/about">Meet Sol & Sage →</Link></section>
  <section className="services"><div className="section-head"><div><p className="eyebrow">THE MENU</p><h2>Services with intention.</h2></div><Link className="text-link" href="/services">View all services →</Link></div><div className="service-grid">{services.map((s,i)=><Link className="service-card" href={'/services/'+serviceSlugs[i]} key={s}><span>0{i+1}</span><h3>{s}</h3><b>↗</b></Link>)}</div></section>
  <section className="home-gallery"><div className="section-head"><div><p className="eyebrow">THE LOOKBOOK</p><h2>Recent looks.</h2></div><Link className="text-link" href="/gallery">View the gallery →</Link></div><div className="mini-gallery">{looks.map(([src,alt],i)=><Link href="/gallery" key={src}><Image src={src} alt={alt+' in a Santa Barbara beauty studio'} fill sizes="(max-width:700px) 50vw, 25vw"/><span>LOOK {String(i+1).padStart(2,'0')}</span></Link>)}</div></section>
  <section className="feature"><div className="feature-image"><span>COLOR / BALAYAGE</span></div><div className="feature-copy"><p className="eyebrow">YOUR SIGNATURE LOOK</p><h2>Color that feels like you.</h2><p>From subtle dimension to a complete refresh, every color appointment begins with a thoughtful conversation and ends with a look made for your life.</p><Link className="button dark" href="/services/highlights-balayage">Explore color</Link></div></section>
  <section className="home-panels"><article><p className="eyebrow">WHY SOL & SAGE</p><h2>Personal, calm, and considered.</h2><p>The studio concept is designed for people who want a clear conversation, a thoughtful plan, and a result that feels connected to their own style.</p><Link className="text-link" href="/about">About the studio →</Link></article><article><p className="eyebrow">BRIDAL & SPECIAL EVENTS</p><h2>Beauty for meaningful moments.</h2><p>Explore a demo concept for event styling, makeup, and the details that help a special look feel intentional.</p><Link className="text-link" href="/services/bridal-special-events">Explore event beauty →</Link></article></section>
  <section className="process"><p className="eyebrow">OUR PROCESS</p><h2>What to expect.</h2><div className="process-grid"><div><span>01</span><h3>Talk it through</h3><p>Start with your goals, references, routine, and the feeling you want.</p></div><div><span>02</span><h3>Shape the plan</h3><p>Use the service conversation to organize the direction for your visit.</p></div><div><span>03</span><h3>Make it yours</h3><p>Finish with a look designed to feel natural to your everyday life.</p></div></div></section>
  <section className="home-reviews"><p className="eyebrow">KIND WORDS</p><h2>Notes from the chair.</h2><p className="demo-note">Sample testimonials for demonstration purposes.</p><div className="quotes"><blockquote>“A calm, considered experience from start to finish.”<small>— Sample testimonial</small></blockquote><blockquote>“The kind of beauty appointment that feels completely personal.”<small>— Sample testimonial</small></blockquote></div><Link className="text-link" href="/reviews">Read sample reviews →</Link></section>
  <section className="home-faq"><p className="eyebrow">GOOD TO KNOW</p><h2>Questions, answered.</h2><details><summary>Can I reserve online through this site?<span>+</span></summary><p>Not currently. Booking is a visual demonstration and does not create a real appointment or show availability.</p></details><details><summary>What if I am not sure which service to choose?<span>+</span></summary><p>Start with a conversation about your goal. The service pages can help organize the questions to bring.</p></details><Link className="text-link" href="/faq">View all FAQs →</Link></section>
  <section className="cta"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Make space for<br/><em>your next look.</em></h2><Link className="button dark" href="/book">Book an Appointment</Link></section>
 </main>}
