import Link from 'next/link'
import Image from 'next/image'
import {notFound} from 'next/navigation'
import type {Metadata} from 'next'

type Service={title:string;intro:string;focus:string;points:string[];steps:string[];questions:string[];layout:string;photo:string;alt:string}
const esSlugs:Record<string,string>={'haircuts-styling':'cortes-y-peinados','hair-color':'color-de-cabello','highlights-balayage':'luces-y-balayage','blowouts':'brushing','hair-treatments':'tratamientos-para-el-cabello','bridal-special-events':'novias-y-eventos-especiales','makeup-services':'servicios-de-maquillaje'}
const data:Record<string,Service>={
 'haircuts-styling':{title:'Haircuts & Styling',intro:'A considered cut and finish shaped around your texture, routine, and personal point of view.',focus:'The right shape should feel natural in the salon and make sense when you style it at home.',points:['Conversation about length, movement, and routine','Shape and texture adapted to your hair','A finish that shows the direction clearly'],steps:['Talk it through','Shape the cut','Learn the finish'],questions:['Looking for a refresh or a complete change?','What should feel easier about your everyday styling?'],layout:'layout-split',photo:'/images/haircuts-styling.webp',alt:'Haircut and styling consultation in a Santa Barbara salon'},
 'hair-color':{title:'Hair Color',intro:'Personalized color designed to complement your complexion, lifestyle, and the way you want to show up.',focus:'Color planning starts with your goal and your hair history, so the direction feels considered before the first application.',points:['Review your current tone and color history','Choose a direction that fits your routine','Plan tone, placement, and next steps together'],steps:['Share the vision','Map the color','Refine the finish'],questions:['Are you ready for a subtle shift or a new tone?','What should we know about your previous color?'],layout:'layout-editorial',photo:'/images/hair-color.webp',alt:'Hair color consultation in a Santa Barbara salon'},
 'highlights-balayage':{title:'Highlights & Balayage',intro:'Dimensional color with a soft, luminous finish and a grow-out that feels natural.',focus:'Thoughtful placement creates dimension without making the look feel overworked.',points:['Consultation around brightness and contrast','Customized placement for your features','Maintenance conversation for the look you want'],steps:['Set the dimension','Place the light','Finish with tone'],questions:['How much brightness feels right for you?','What kind of maintenance feels realistic?'],layout:'layout-feature-grid',photo:'/images/highlights-balayage.webp',alt:'Highlights and balayage result in a Santa Barbara salon'},
 'blowouts':{title:'Blowouts',intro:'A polished, touchable finish for celebrations, photos, weekends, or simply feeling put together.',focus:'Choose the feeling: movement, volume, softness, or a sleek finish that carries you through the occasion.',points:['Discuss the finish and occasion','Prepare hair for shape and movement','Polish the details without losing natural texture'],steps:['Choose the mood','Build the shape','Polish the finish'],questions:['Need movement, volume, or sleekness?','What should the finished look feel like?'],layout:'layout-immersive',photo:'/images/blowouts.webp',alt:'Blowout styling with volume in a Santa Barbara salon'},
 'hair-treatments':{title:'Hair Treatments',intro:'Focused care for softness, shine, manageability, and the needs of your hair today.',focus:'A treatment conversation looks at what you are noticing—dryness, damage, or a lack of softness—and what support fits your routine.',points:['Talk through dryness, damage, or manageability','Choose a focused care direction','Discuss simple maintenance between visits'],steps:['Notice the need','Choose the care','Keep the feel'],questions:['Is your hair feeling dry or difficult to style?','What have you tried recently at home?'],layout:'layout-process',photo:'/images/hair-treatments.webp',alt:'Hair treatment consultation in a Santa Barbara salon'},
 'bridal-special-events':{title:'Bridal & Special Events',intro:'Beauty planning and styling for meaningful days, from the first conversation to the final detail.',focus:'The experience is organized around timing, references, and a look that feels like you in the moment that matters.',points:['Consultation for the event and styling direction','Trial conversation for shape, texture, and details','A clear plan for the day and the people involved'],steps:['Share the vision','Refine the trial','Plan the day'],questions:['Are you planning a wedding or special event?','What timing and coordination details should we discuss?'],layout:'layout-timeline',photo:'/images/bridal-special-events.webp',alt:'Bridal updo styling consultation in a Santa Barbara salon'},
 'makeup-services':{title:'Makeup Services',intro:'Modern, wearable makeup that enhances your features and feels like you—only a little more luminous.',focus:'Makeup begins with the occasion, your preferences, and the level of polish that still feels comfortable.',points:['Consultation around the occasion and references','Skin preparation before makeup application','A finish considered for comfort and longevity'],steps:['Prepare the skin','Build the look','Finish with intention'],questions:['Looking for a soft, polished, or statement look?','What do you want the makeup to feel like throughout the event?'],layout:'layout-split-reverse',photo:'/images/makeup-services.webp',alt:'Makeup application in a Santa Barbara salon'}
}
export function generateMetadata({params}:{params:{slug:string}}):Metadata{const item=data[params.slug];if(!item)return{};return{title:`${item.title} | Sol & Sage Beauty Studio`,description:item.intro,alternates:{canonical:`/services/${params.slug}`,languages:{'en-US':`/services/${params.slug}`,'es-US':`/es/servicios/${esSlugs[params.slug]}`}},openGraph:{url:`/services/${params.slug}`,images:[{url:item.photo,width:1440,height:1024,alt:item.alt}],title:`${item.title} | Sol & Sage Beauty Studio`,description:item.intro}}}
export default function Service({params}:{params:{slug:string}}){const item=data[params.slug];if(!item)notFound();return <main className={`inner service-detail ${item.layout} service-${params.slug}`}><section className="service-hero"><div className="service-heading"><p className="eyebrow">SOL & SAGE · SERVICES</p><h1>{item.title}</h1><p className="lead">{item.intro}</p></div><div className="service-hero-image"><Image src={item.photo} alt={item.alt} fill sizes="(max-width:800px) 100vw, 55vw" priority/></div></section><section className="service-focus"><p className="eyebrow">THE APPROACH</p><h2>{item.focus}</h2><div className="service-points">{item.points.map((point,i)=><div key={point}><span>0{i+1}</span><p>{point}</p></div>)}</div></section><section className="service-process"><p className="eyebrow">WHAT TO EXPECT</p><div className="service-process-grid">{item.steps.map((step,i)=><div key={step}><span>0{i+1}</span><h3>{step}</h3><p>We shape this part of the experience around your goals, references, and everyday preferences.</p></div>)}</div></section><section className="service-faq"><p className="eyebrow">A GOOD PLACE TO START</p><h2>Bring your questions.</h2><div className="service-questions">{item.questions.map(q=><div key={q}><span>ASK YOURSELF</span><h3>{q}</h3><p>We can use your appointment conversation to clarify the direction before choosing the details.</p></div>)}</div></section><section className="service-cta"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Make space for your next look.</h2><Link className="button" href="/book">Book an Appointment</Link><Link className="text-link" href="/services">View all services →</Link></section></main>}
