import Link from 'next/link'
import Image from 'next/image'
import {notFound} from 'next/navigation'
import type {Metadata} from 'next'

type Service={title:string;intro:string;focus:string;points:string[];steps:string[];questions:string[];layout:string;photo:string;alt:string}
const enSlugs:Record<string,string>={'cortes-y-peinados':'haircuts-styling','color-de-cabello':'hair-color','luces-y-balayage':'highlights-balayage','brushing':'blowouts','tratamientos-para-el-cabello':'hair-treatments','novias-y-eventos-especiales':'bridal-special-events','servicios-de-maquillaje':'makeup-services'}
const services:Record<string,Service>={
 'cortes-y-peinados':{title:'Cortes y peinados',intro:'Un corte pensado para tu textura, el largo que prefieres y la rutina que quieres mantener.',focus:'La forma adecuada debe verse natural al salir del estudio y ser fácil de manejar cuando te peinas en casa.',points:['Conversación sobre largo, movimiento y rutina','Forma y textura adaptadas a tu cabello','Un acabado que te ayuda a entender el nuevo corte'],steps:['Hablar de tus ideas','Dar forma al corte','Aprender a peinarlo'],questions:['¿Quieres renovar tu corte o cambiarlo por completo?','¿Qué te gustaría facilitar en tu rutina diaria?'],layout:'layout-split',photo:'/images/haircuts-styling.webp',alt:'Consulta de corte y peinado en un estudio de Santa Barbara'},
 'color-de-cabello':{title:'Coloración del cabello',intro:'Color personalizado que parte de tu objetivo, tu historial de color y una conversación honesta.',focus:'La planificación comienza con tu meta y el historial de tu cabello para definir el camino antes de aplicar el color.',points:['Revisar tu tono actual y tu historial de color','Elegir una dirección que se adapte a tu rutina','Hablar sobre el tono, la distribución y los siguientes pasos'],steps:['Compartir tu idea','Diseñar la distribución del color','Perfeccionar el acabado'],questions:['¿Buscas un cambio sutil o un tono completamente nuevo?','¿Qué debemos saber sobre tus coloraciones anteriores?'],layout:'layout-editorial',photo:'/images/hair-color.webp',alt:'Consulta de coloración del cabello en un estudio de Santa Barbara'},
 'luces-y-balayage':{title:'Luces y balayage',intro:'Dimensión y luminosidad adaptadas al tono que imaginas y al mantenimiento que te resulta práctico.',focus:'Una distribución bien pensada crea dimensión sin que el resultado se vea excesivo.',points:['Conversación sobre luminosidad y contraste','Distribución personalizada para favorecer tus facciones','Mantenimiento acorde con el estilo que buscas'],steps:['Definir la dimensión','Distribuir los puntos de luz','Ajustar el tono final'],questions:['¿Qué nivel de luminosidad te gustaría explorar?','¿Qué mantenimiento te resulta realista?'],layout:'layout-feature-grid',photo:'/images/highlights-balayage.webp',alt:'Resultado de luces y balayage en un estudio de Santa Barbara'},
 'brushing':{title:'Secado y peinado',intro:'Un acabado con movimiento, volumen o suavidad para acompañar tu ocasión y tu estilo.',focus:'Elige cómo quieres sentirte: con movimiento, volumen, suavidad o un acabado más pulido para la ocasión.',points:['Hablar sobre el acabado y la ocasión','Preparar el cabello para darle forma y movimiento','Cuidar los detalles sin perder tu textura natural'],steps:['Elegir el estilo','Crear la forma','Perfeccionar el acabado'],questions:['¿Prefieres volumen, movimiento o un acabado pulido?','¿Cómo quieres que se sienta el resultado final?'],layout:'layout-immersive',photo:'/images/blowouts.webp',alt:'Secado y peinado con volumen en un estudio de Santa Barbara'},
 'tratamientos-para-el-cabello':{title:'Tratamientos capilares',intro:'Una conversación sobre las necesidades visibles de tu cabello para elegir el cuidado adecuado.',focus:'Revisamos lo que notas —resequedad, daño o falta de suavidad— y qué tipo de cuidado puede adaptarse a tu rutina.',points:['Hablar sobre resequedad, daño o dificultad para peinarlo','Elegir el cuidado más adecuado','Comentar un mantenimiento sencillo entre visitas'],steps:['Observar las necesidades','Elegir el tratamiento','Prolongar la sensación'],questions:['¿Tu cabello se siente seco o difícil de manejar?','¿Qué productos o tratamientos has probado en casa?'],layout:'layout-process',photo:'/images/hair-treatments.webp',alt:'Consulta de tratamiento capilar en un estudio de Santa Barbara'},
 'novias-y-eventos-especiales':{title:'Novias y eventos especiales',intro:'Planificación de un estilo para tu evento, con inspiración, referencias y coordinación de los detalles importantes.',focus:'La experiencia se organiza en torno al horario, tus referencias y un estilo que realmente se sienta como tú.',points:['Consulta sobre el evento y el estilo deseado','Prueba para definir forma, textura y detalles','Plan claro para ese día y las personas involucradas'],steps:['Compartir tu visión','Perfeccionar la prueba','Planificar el gran día'],questions:['¿Estás planeando una boda o un evento especial?','¿Qué detalles de horario y coordinación debemos considerar?'],layout:'layout-timeline',photo:'/images/bridal-special-events.webp',alt:'Consulta de peinado para novia en un estudio de Santa Barbara'},
 'servicios-de-maquillaje':{title:'Maquillaje',intro:'Maquillaje pensado para la ocasión, el estilo que deseas, tus referencias y tus preferencias personales.',focus:'Todo comienza con la ocasión, tus preferencias y el nivel de definición con el que te sientas cómoda.',points:['Conversación sobre la ocasión y tus referencias','Preparación de la piel antes del maquillaje','Acabado pensado para brindar comodidad y duración'],steps:['Preparar la piel','Crear el estilo','Cuidar los detalles finales'],questions:['¿Buscas un estilo suave, definido o más expresivo?','¿Cómo quieres que se sienta el maquillaje durante el evento?'],layout:'layout-split-reverse',photo:'/images/makeup-services.webp',alt:'Aplicación de maquillaje en un estudio de Santa Barbara'}
}
export function generateMetadata({params}:{params:{slug:string[]}}):Metadata{const slug=params.slug[params.slug.length-1];const item=services[slug];if(!item)return{};return{title:`${item.title} | Sol & Sage Beauty Studio`,description:item.intro,alternates:{canonical:`/es/servicios/${slug}`,languages:{'en-US':`/services/${enSlugs[slug]}`,'es-US':`/es/servicios/${slug}`}},openGraph:{url:`/es/servicios/${slug}`,images:[{url:item.photo,width:1440,height:1024,alt:item.alt}],title:`${item.title} | Sol & Sage Beauty Studio`,description:item.intro}}}
export default function SpanishDynamic({params}:{params:{slug:string[]}}){const slug=params.slug[params.slug.length-1];const item=services[slug];if(!item)notFound();return <main className={`inner service-detail ${item.layout} service-${slug}`}><section className="service-hero"><div className="service-heading"><p className="eyebrow">SOL & SAGE · SERVICIOS</p><h1>{item.title}</h1><p className="lead">{item.intro}</p></div><div className="service-hero-image"><Image src={item.photo} alt={item.alt} fill sizes="(max-width:800px) 100vw, 55vw" priority/></div></section><section className="service-focus"><p className="eyebrow">NUESTRO ENFOQUE</p><h2>{item.focus}</h2><div className="service-points">{item.points.map((point,i)=><div key={point}><span>0{i+1}</span><p>{point}</p></div>)}</div></section><section className="service-process"><p className="eyebrow">QUÉ PUEDES ESPERAR</p><div className="service-process-grid">{item.steps.map((step,i)=><div key={step}><span>0{i+1}</span><h3>{step}</h3><p>Adaptamos esta parte de la experiencia a tus objetivos, referencias y preferencias de todos los días.</p></div>)}</div></section><section className="service-faq"><p className="eyebrow">UN BUEN PUNTO DE PARTIDA</p><h2>Cuéntanos tus ideas.</h2><div className="service-questions">{item.questions.map(q=><div key={q}><span>PARA CONVERSAR</span><h3>{q}</h3><p>Esta conversación nos ayudará a definir la dirección adecuada antes de elegir los detalles.</p></div>)}</div></section><section className="service-cta"><p className="eyebrow">CUANDO QUIERAS</p><h2>Haz espacio para tu próximo estilo.</h2><Link className="button" href="/es/agendar">Agenda una cita</Link><Link className="text-link" href="/es/servicios">Ver todos los servicios →</Link></section></main>}
