import Link from 'next/link'
import Image from 'next/image'
import {notFound} from 'next/navigation'
import type {Metadata} from 'next'

type Service={title:string;intro:string;focus:string;points:string[];steps:string[];questions:string[];layout:string;photo:string;alt:string}
const enSlugs:Record<string,string>={'cortes-y-peinados':'haircuts-styling','color-de-cabello':'hair-color','luces-y-balayage':'highlights-balayage','brushing':'blowouts','tratamientos-para-el-cabello':'hair-treatments','novias-y-eventos-especiales':'bridal-special-events','servicios-de-maquillaje':'makeup-services'}
const services:Record<string,Service>={
 'cortes-y-peinados':{title:'Cortes y Peinados',intro:'Un corte pensado para tu textura, tu largo y la rutina que quieres mantener.',focus:'La forma correcta debe sentirse natural en el estudio y tener sentido cuando lo peinas en casa.',points:['Conversación sobre largo, movimiento y rutina','Forma y textura adaptadas a tu cabello','Un acabado que muestra claramente la dirección'],steps:['Conversarlo','Dar forma al corte','Entender el acabado'],questions:['¿Buscas refrescar tu corte o cambiarlo por completo?','¿Qué te gustaría hacer más fácil en tu peinado diario?'],layout:'layout-split',photo:'/images/haircuts-styling.webp',alt:'Consulta de corte y peinado en un estudio de Santa Barbara'},
 'color-de-cabello':{title:'Color de Cabello',intro:'Color personalizado que parte de tu objetivo, tu historial y una conversación honesta.',focus:'La planeación comienza con tu meta y el historial de tu cabello para definir la dirección antes de aplicar el color.',points:['Revisar tu tono actual y tu historial','Elegir una dirección que encaje con tu rutina','Conversar sobre tono, colocación y siguientes pasos'],steps:['Compartir la idea','Mapear el color','Refinar el acabado'],questions:['¿Buscas un cambio sutil o un tono nuevo?','¿Qué debemos saber sobre tu color anterior?'],layout:'layout-editorial',photo:'/images/hair-color.webp',alt:'Consulta de color de cabello en un estudio de Santa Barbara'},
 'luces-y-balayage':{title:'Luces y Balayage',intro:'Dimensión y luminosidad adaptadas al tono que imaginas y al mantenimiento que te resulta práctico.',focus:'La colocación pensada crea dimensión sin que el resultado se sienta excesivo.',points:['Conversación sobre claridad y contraste','Colocación personalizada para tus facciones','Mantenimiento relacionado con el look que buscas'],steps:['Definir la dimensión','Colocar la luz','Terminar con tono'],questions:['¿Qué nivel de claridad te gustaría explorar?','¿Qué mantenimiento se siente realista para ti?'],layout:'layout-feature-grid',photo:'/images/highlights-balayage.webp',alt:'Resultado de luces y balayage en un estudio de Santa Barbara'},
 'brushing':{title:'Brushing',intro:'Un acabado con movimiento, volumen o suavidad para acompañar tu ocasión y tu estilo.',focus:'Elige la sensación: movimiento, volumen, suavidad o un acabado pulido para tu ocasión.',points:['Conversar sobre el acabado y la ocasión','Preparar el cabello para forma y movimiento','Pulir los detalles sin perder tu textura natural'],steps:['Elegir el estilo','Crear la forma','Pulir el acabado'],questions:['¿Prefieres volumen, movimiento o un acabado pulido?','¿Cómo quieres sentir el resultado?'],layout:'layout-immersive',photo:'/images/blowouts.webp',alt:'Brushing con volumen en un estudio de Santa Barbara'},
 'tratamientos-para-el-cabello':{title:'Tratamientos para el Cabello',intro:'Una conversación sobre las necesidades visibles de tu cabello para elegir un enfoque adecuado.',focus:'Revisamos lo que notas—resequedad, daño o falta de suavidad—y qué cuidado puede encajar con tu rutina.',points:['Conversar sobre resequedad, daño o manejo','Elegir una dirección de cuidado','Hablar de mantenimiento sencillo entre visitas'],steps:['Observar la necesidad','Elegir el cuidado','Mantener la sensación'],questions:['¿Tu cabello se siente seco o difícil de peinar?','¿Qué has probado recientemente en casa?'],layout:'layout-process',photo:'/images/hair-treatments.webp',alt:'Consulta de tratamiento capilar en un estudio de Santa Barbara'},
 'novias-y-eventos-especiales':{title:'Novias y Eventos Especiales',intro:'Planeación de un look para tu evento, con inspiración, referencias y coordinación de los detalles importantes.',focus:'La experiencia se organiza alrededor del horario, tus referencias y un look que se sienta como tú.',points:['Consulta sobre el evento y la dirección del look','Conversación de prueba sobre forma, textura y detalles','Plan claro para el día y las personas involucradas'],steps:['Compartir la visión','Refinar la prueba','Planear el día'],questions:['¿Estás planeando una boda o un evento especial?','¿Qué detalles de horario y coordinación debemos conversar?'],layout:'layout-timeline',photo:'/images/bridal-special-events.webp',alt:'Consulta de peinado nupcial en un estudio de Santa Barbara'},
 'servicios-de-maquillaje':{title:'Servicios de Maquillaje',intro:'Maquillaje guiado por la ocasión, tu estilo deseado, tus referencias y tus preferencias personales.',focus:'El maquillaje comienza con la ocasión, tus preferencias y el nivel de pulido que todavía se siente cómodo.',points:['Conversación sobre la ocasión y referencias','Preparación de la piel antes de aplicar maquillaje','Acabado pensado para comodidad y duración'],steps:['Preparar la piel','Construir el look','Terminar con intención'],questions:['¿Buscas un look suave, pulido o más expresivo?','¿Cómo quieres sentir el maquillaje durante el evento?'],layout:'layout-split-reverse',photo:'/images/makeup-services.webp',alt:'Aplicación de maquillaje en un estudio de Santa Barbara'}
}
export function generateMetadata({params}:{params:{slug:string[]}}):Metadata{const slug=params.slug[params.slug.length-1];const item=services[slug];if(!item)return{};return{title:`${item.title} | Sol & Sage Beauty Studio`,description:item.intro,alternates:{canonical:`/es/servicios/${slug}`,languages:{'en-US':`/services/${enSlugs[slug]}`,'es-US':`/es/servicios/${slug}`}},openGraph:{url:`/es/servicios/${slug}`,images:[{url:item.photo,width:1440,height:1024,alt:item.alt}],title:`${item.title} | Sol & Sage Beauty Studio`,description:item.intro}}}
export default function SpanishDynamic({params}:{params:{slug:string[]}}){const slug=params.slug[params.slug.length-1];const item=services[slug];if(!item)notFound();return <main className={`inner service-detail ${item.layout} service-${slug}`}><section className="service-hero"><div className="service-heading"><p className="eyebrow">SOL & SAGE · SERVICIOS</p><h1>{item.title}</h1><p className="lead">{item.intro}</p></div><div className="service-hero-image"><Image src={item.photo} alt={item.alt} fill sizes="(max-width:800px) 100vw, 55vw" priority/></div></section><section className="service-focus"><p className="eyebrow">EL ENFOQUE</p><h2>{item.focus}</h2><div className="service-points">{item.points.map((point,i)=><div key={point}><span>0{i+1}</span><p>{point}</p></div>)}</div></section><section className="service-process"><p className="eyebrow">QUÉ PUEDES ESPERAR</p><div className="service-process-grid">{item.steps.map((step,i)=><div key={step}><span>0{i+1}</span><h3>{step}</h3><p>Construimos esta parte de la experiencia alrededor de tus metas, referencias y preferencias diarias.</p></div>)}</div></section><section className="service-faq"><p className="eyebrow">UN BUEN PUNTO DE PARTIDA</p><h2>Trae tus preguntas.</h2><div className="service-questions">{item.questions.map(q=><div key={q}><span>PARA CONVERSAR</span><h3>{q}</h3><p>Podemos usar tu conversación para aclarar la dirección antes de elegir los detalles.</p></div>)}</div></section><section className="service-cta"><p className="eyebrow">CUANDO ESTÉS LISTA</p><h2>Haz espacio para tu próximo look.</h2><Link className="button" href="/es/agendar">Agenda una Cita</Link><Link className="text-link" href="/es/servicios">Ver todos los servicios →</Link></section></main>}
